# Generated by Django 5.2.7 on 2025-10-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('types', models.JSONField()),
                ('weaknesses', models.JSONField(blank=True, null=True)),
                ('evolutions', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
